export const TIMER_CONSTANTS = {
  INTERVAL_MS: 1000,
  SECONDS_PER_MINUTE: 60,
  TIMER_FONT_SIZE: 72,
  FAB_BOTTOM_POSITION: 50,
  FAB_SIDE_POSITION: 20,
  FAB_SIZE: 60,
  FAB_BORDER_RADIUS: 15,
  BUTTON_LONG_PRESS_THRESHOLD: 500,
} as const;
